name: Node.js CI

on:
  push:
    branches: Styling-tentative
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm i
    - run: npm run build 
    - run: npm test
